export const TRANSPORT_TYPES = {
  // Instant
  MICRO_EXPRESS: "MICRO_EXPRESS",
  MICRO_BATCH: "MICRO_BATCH",
  MOTO_EXPRESS: "MOTO_EXPRESS",
  MOTO_BATCH: "MOTO_BATCH",

  // Vans
  SMALL_VAN: "SMALL_VAN",
  MEDIUM_VAN: "MEDIUM_VAN",
  LARGE_VAN: "LARGE_VAN",

  // Trucks
  TRUCK_5T: "TRUCK_5T",
  TRUCK_10T: "TRUCK_10T",

  // Specialty
  FLATBED_5T: "FLATBED_5T",
  TIPPER_5T: "TIPPER_5T",
  REFRIGERATED_5T: "REFRIGERATED_5T",

  MAXI: "MAXI",
};
