/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateCompanyVehicle = /* GraphQL */ `
  subscription OnCreateCompanyVehicle(
    $filter: ModelSubscriptionCompanyVehicleFilterInput
  ) {
    onCreateCompanyVehicle(filter: $filter) {
      id
      vehicleType
      model
      plateNumber
      couriercompanyID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateCompanyVehicle = /* GraphQL */ `
  subscription OnUpdateCompanyVehicle(
    $filter: ModelSubscriptionCompanyVehicleFilterInput
  ) {
    onUpdateCompanyVehicle(filter: $filter) {
      id
      vehicleType
      model
      plateNumber
      couriercompanyID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteCompanyVehicle = /* GraphQL */ `
  subscription OnDeleteCompanyVehicle(
    $filter: ModelSubscriptionCompanyVehicleFilterInput
  ) {
    onDeleteCompanyVehicle(filter: $filter) {
      id
      vehicleType
      model
      plateNumber
      couriercompanyID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreateCourierCompany = /* GraphQL */ `
  subscription OnCreateCourierCompany(
    $filter: ModelSubscriptionCourierCompanyFilterInput
  ) {
    onCreateCourierCompany(filter: $filter) {
      id
      sub
      firstName
      lastName
      profilePic
      address
      lat
      lng
      landmark
      phoneNumber
      email
      adminFirstName
      adminLastName
      adminPhoneNumber
      bankName
      CompanyVehicles {
        nextToken
        startedAt
        __typename
      }
      accountNumber
      push_token
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateCourierCompany = /* GraphQL */ `
  subscription OnUpdateCourierCompany(
    $filter: ModelSubscriptionCourierCompanyFilterInput
  ) {
    onUpdateCourierCompany(filter: $filter) {
      id
      sub
      firstName
      lastName
      profilePic
      address
      lat
      lng
      landmark
      phoneNumber
      email
      adminFirstName
      adminLastName
      adminPhoneNumber
      bankName
      CompanyVehicles {
        nextToken
        startedAt
        __typename
      }
      accountNumber
      push_token
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteCourierCompany = /* GraphQL */ `
  subscription OnDeleteCourierCompany(
    $filter: ModelSubscriptionCourierCompanyFilterInput
  ) {
    onDeleteCourierCompany(filter: $filter) {
      id
      sub
      firstName
      lastName
      profilePic
      address
      lat
      lng
      landmark
      phoneNumber
      email
      adminFirstName
      adminLastName
      adminPhoneNumber
      bankName
      CompanyVehicles {
        nextToken
        startedAt
        __typename
      }
      accountNumber
      push_token
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreatePayout = /* GraphQL */ `
  subscription OnCreatePayout($filter: ModelSubscriptionPayoutFilterInput) {
    onCreatePayout(filter: $filter) {
      id
      courierID
      amount
      status
      bankName
      accountNumber
      reference
      walletID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdatePayout = /* GraphQL */ `
  subscription OnUpdatePayout($filter: ModelSubscriptionPayoutFilterInput) {
    onUpdatePayout(filter: $filter) {
      id
      courierID
      amount
      status
      bankName
      accountNumber
      reference
      walletID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeletePayout = /* GraphQL */ `
  subscription OnDeletePayout($filter: ModelSubscriptionPayoutFilterInput) {
    onDeletePayout(filter: $filter) {
      id
      courierID
      amount
      status
      bankName
      accountNumber
      reference
      walletID
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreateTransaction = /* GraphQL */ `
  subscription OnCreateTransaction(
    $filter: ModelSubscriptionTransactionFilterInput
  ) {
    onCreateTransaction(filter: $filter) {
      id
      walletID
      type
      amount
      description
      orderID
      paymentID
      status
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateTransaction = /* GraphQL */ `
  subscription OnUpdateTransaction(
    $filter: ModelSubscriptionTransactionFilterInput
  ) {
    onUpdateTransaction(filter: $filter) {
      id
      walletID
      type
      amount
      description
      orderID
      paymentID
      status
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteTransaction = /* GraphQL */ `
  subscription OnDeleteTransaction(
    $filter: ModelSubscriptionTransactionFilterInput
  ) {
    onDeleteTransaction(filter: $filter) {
      id
      walletID
      type
      amount
      description
      orderID
      paymentID
      status
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreateWallet = /* GraphQL */ `
  subscription OnCreateWallet($filter: ModelSubscriptionWalletFilterInput) {
    onCreateWallet(filter: $filter) {
      id
      ownerID
      ownerType
      balance
      pendingBalance
      totalEarnings
      transactions {
        nextToken
        startedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateWallet = /* GraphQL */ `
  subscription OnUpdateWallet($filter: ModelSubscriptionWalletFilterInput) {
    onUpdateWallet(filter: $filter) {
      id
      ownerID
      ownerType
      balance
      pendingBalance
      totalEarnings
      transactions {
        nextToken
        startedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteWallet = /* GraphQL */ `
  subscription OnDeleteWallet($filter: ModelSubscriptionWalletFilterInput) {
    onDeleteWallet(filter: $filter) {
      id
      ownerID
      ownerType
      balance
      pendingBalance
      totalEarnings
      transactions {
        nextToken
        startedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreatePayment = /* GraphQL */ `
  subscription OnCreatePayment($filter: ModelSubscriptionPaymentFilterInput) {
    onCreatePayment(filter: $filter) {
      id
      orderID
      userID
      amount
      currency
      status
      paymentMethod
      provider
      reference
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      user {
        id
        sub
        firstName
        lastName
        email
        phoneNumber
        profilePic
        address
        exactAddress
        lat
        lng
        isBlocked
        push_token
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdatePayment = /* GraphQL */ `
  subscription OnUpdatePayment($filter: ModelSubscriptionPaymentFilterInput) {
    onUpdatePayment(filter: $filter) {
      id
      orderID
      userID
      amount
      currency
      status
      paymentMethod
      provider
      reference
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      user {
        id
        sub
        firstName
        lastName
        email
        phoneNumber
        profilePic
        address
        exactAddress
        lat
        lng
        isBlocked
        push_token
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeletePayment = /* GraphQL */ `
  subscription OnDeletePayment($filter: ModelSubscriptionPaymentFilterInput) {
    onDeletePayment(filter: $filter) {
      id
      orderID
      userID
      amount
      currency
      status
      paymentMethod
      provider
      reference
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      user {
        id
        sub
        firstName
        lastName
        email
        phoneNumber
        profilePic
        address
        exactAddress
        lat
        lng
        isBlocked
        push_token
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreateOffer = /* GraphQL */ `
  subscription OnCreateOffer($filter: ModelSubscriptionOfferFilterInput) {
    onCreateOffer(filter: $filter) {
      id
      orderID
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      courierID
      courier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      senderType
      amount
      status
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateOffer = /* GraphQL */ `
  subscription OnUpdateOffer($filter: ModelSubscriptionOfferFilterInput) {
    onUpdateOffer(filter: $filter) {
      id
      orderID
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      courierID
      courier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      senderType
      amount
      status
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteOffer = /* GraphQL */ `
  subscription OnDeleteOffer($filter: ModelSubscriptionOfferFilterInput) {
    onDeleteOffer(filter: $filter) {
      id
      orderID
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      courierID
      courier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      senderType
      amount
      status
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreateOrder = /* GraphQL */ `
  subscription OnCreateOrder($filter: ModelSubscriptionOrderFilterInput) {
    onCreateOrder(filter: $filter) {
      id
      recipientName
      recipientNumber
      recipientNumber2
      orderDetails
      originAddress
      originState
      originLat
      originLng
      destinationAddress
      destinationState
      destinationLat
      destinationLng
      tripType
      distance
      transportationType
      vehicleClass
      status
      hasNewOffer
      lastOfferAt
      lastOfferSenderType
      loadCategory
      isInterState
      estimatedMinPrice
      estimatedMaxPrice
      initialOfferPrice
      loadingFee
      unloadingFee
      floorSurcharge
      fragileSurcharge
      extrasTotal
      totalPrice
      operationalFare
      courierEarnings
      commissionAmount
      platformFee
      platformServiceRevenue
      vatAmount
      platformNetRevenue
      deliveryVerificationCode
      declaredWeightBracket
      senderPreTransferPhotos
      senderPreTransferVideo
      senderPreTransferRecordedAt
      senderPreTransferLocalPhotos
      senderPreTransferLocalVideo
      mediaUploadStatus
      courierPreTransferUploadStatus
      courierPostLoadingUploadStatus
      dropoffUploadStatus
      courierPreTransferPhotos
      courierPreTransferVideo
      courierPreTransferRecordedAt
      courierPreTransferLocalPhotos
      courierPreTransferLocalVideo
      courierPostLoadingPhotos
      courierPostLoadingVideo
      courierPostLoadingLocalPhotos
      courierPostLoadingLocalVideo
      dropoffArrivalPhotos
      dropoffArrivalVideo
      dropoffArrivalLocalPhotos
      dropoffArrivalLocalVideo
      postDeliveryPhotos
      postDeliveryVideo
      pickupLoadingResponsibility
      pickupFloorLevel
      pickupFloorLevelPrice
      pickupHasElevator
      dropoffUnloadingResponsibility
      dropoffFloorLevel
      dropoffFloorLevelPrice
      dropoffHasElevator
      acceptedAt
      arrivedPickupAt
      loadingStartedAt
      tripStartedAt
      arrivedDropoffAt
      unloadingCompletedAt
      logisticsCompanyId
      waybillNumber
      waybillPhoto
      logisticsTrackingCode
      logisticsTrackingStatus
      handedOverToLogisticsAt
      logisticsIntakeConfirmedAt
      acceptedOfferID
      paymentStatus
      paymentID
      payoutStatus
      fundsStatus
      assignedCourierId
      assignmentExpiresAt
      assignmentAttempts
      lastAssignedAt
      rejectedCourierIds
      assignmentStatus
      userID
      reviews {
        nextToken
        startedAt
        __typename
      }
      reports {
        nextToken
        startedAt
        __typename
      }
      offers {
        nextToken
        startedAt
        __typename
      }
      assignedCourier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      payments {
        nextToken
        startedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateOrder = /* GraphQL */ `
  subscription OnUpdateOrder($filter: ModelSubscriptionOrderFilterInput) {
    onUpdateOrder(filter: $filter) {
      id
      recipientName
      recipientNumber
      recipientNumber2
      orderDetails
      originAddress
      originState
      originLat
      originLng
      destinationAddress
      destinationState
      destinationLat
      destinationLng
      tripType
      distance
      transportationType
      vehicleClass
      status
      hasNewOffer
      lastOfferAt
      lastOfferSenderType
      loadCategory
      isInterState
      estimatedMinPrice
      estimatedMaxPrice
      initialOfferPrice
      loadingFee
      unloadingFee
      floorSurcharge
      fragileSurcharge
      extrasTotal
      totalPrice
      operationalFare
      courierEarnings
      commissionAmount
      platformFee
      platformServiceRevenue
      vatAmount
      platformNetRevenue
      deliveryVerificationCode
      declaredWeightBracket
      senderPreTransferPhotos
      senderPreTransferVideo
      senderPreTransferRecordedAt
      senderPreTransferLocalPhotos
      senderPreTransferLocalVideo
      mediaUploadStatus
      courierPreTransferUploadStatus
      courierPostLoadingUploadStatus
      dropoffUploadStatus
      courierPreTransferPhotos
      courierPreTransferVideo
      courierPreTransferRecordedAt
      courierPreTransferLocalPhotos
      courierPreTransferLocalVideo
      courierPostLoadingPhotos
      courierPostLoadingVideo
      courierPostLoadingLocalPhotos
      courierPostLoadingLocalVideo
      dropoffArrivalPhotos
      dropoffArrivalVideo
      dropoffArrivalLocalPhotos
      dropoffArrivalLocalVideo
      postDeliveryPhotos
      postDeliveryVideo
      pickupLoadingResponsibility
      pickupFloorLevel
      pickupFloorLevelPrice
      pickupHasElevator
      dropoffUnloadingResponsibility
      dropoffFloorLevel
      dropoffFloorLevelPrice
      dropoffHasElevator
      acceptedAt
      arrivedPickupAt
      loadingStartedAt
      tripStartedAt
      arrivedDropoffAt
      unloadingCompletedAt
      logisticsCompanyId
      waybillNumber
      waybillPhoto
      logisticsTrackingCode
      logisticsTrackingStatus
      handedOverToLogisticsAt
      logisticsIntakeConfirmedAt
      acceptedOfferID
      paymentStatus
      paymentID
      payoutStatus
      fundsStatus
      assignedCourierId
      assignmentExpiresAt
      assignmentAttempts
      lastAssignedAt
      rejectedCourierIds
      assignmentStatus
      userID
      reviews {
        nextToken
        startedAt
        __typename
      }
      reports {
        nextToken
        startedAt
        __typename
      }
      offers {
        nextToken
        startedAt
        __typename
      }
      assignedCourier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      payments {
        nextToken
        startedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteOrder = /* GraphQL */ `
  subscription OnDeleteOrder($filter: ModelSubscriptionOrderFilterInput) {
    onDeleteOrder(filter: $filter) {
      id
      recipientName
      recipientNumber
      recipientNumber2
      orderDetails
      originAddress
      originState
      originLat
      originLng
      destinationAddress
      destinationState
      destinationLat
      destinationLng
      tripType
      distance
      transportationType
      vehicleClass
      status
      hasNewOffer
      lastOfferAt
      lastOfferSenderType
      loadCategory
      isInterState
      estimatedMinPrice
      estimatedMaxPrice
      initialOfferPrice
      loadingFee
      unloadingFee
      floorSurcharge
      fragileSurcharge
      extrasTotal
      totalPrice
      operationalFare
      courierEarnings
      commissionAmount
      platformFee
      platformServiceRevenue
      vatAmount
      platformNetRevenue
      deliveryVerificationCode
      declaredWeightBracket
      senderPreTransferPhotos
      senderPreTransferVideo
      senderPreTransferRecordedAt
      senderPreTransferLocalPhotos
      senderPreTransferLocalVideo
      mediaUploadStatus
      courierPreTransferUploadStatus
      courierPostLoadingUploadStatus
      dropoffUploadStatus
      courierPreTransferPhotos
      courierPreTransferVideo
      courierPreTransferRecordedAt
      courierPreTransferLocalPhotos
      courierPreTransferLocalVideo
      courierPostLoadingPhotos
      courierPostLoadingVideo
      courierPostLoadingLocalPhotos
      courierPostLoadingLocalVideo
      dropoffArrivalPhotos
      dropoffArrivalVideo
      dropoffArrivalLocalPhotos
      dropoffArrivalLocalVideo
      postDeliveryPhotos
      postDeliveryVideo
      pickupLoadingResponsibility
      pickupFloorLevel
      pickupFloorLevelPrice
      pickupHasElevator
      dropoffUnloadingResponsibility
      dropoffFloorLevel
      dropoffFloorLevelPrice
      dropoffHasElevator
      acceptedAt
      arrivedPickupAt
      loadingStartedAt
      tripStartedAt
      arrivedDropoffAt
      unloadingCompletedAt
      logisticsCompanyId
      waybillNumber
      waybillPhoto
      logisticsTrackingCode
      logisticsTrackingStatus
      handedOverToLogisticsAt
      logisticsIntakeConfirmedAt
      acceptedOfferID
      paymentStatus
      paymentID
      payoutStatus
      fundsStatus
      assignedCourierId
      assignmentExpiresAt
      assignmentAttempts
      lastAssignedAt
      rejectedCourierIds
      assignmentStatus
      userID
      reviews {
        nextToken
        startedAt
        __typename
      }
      reports {
        nextToken
        startedAt
        __typename
      }
      offers {
        nextToken
        startedAt
        __typename
      }
      assignedCourier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      payments {
        nextToken
        startedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreateCourierReport = /* GraphQL */ `
  subscription OnCreateCourierReport(
    $filter: ModelSubscriptionCourierReportFilterInput
  ) {
    onCreateCourierReport(filter: $filter) {
      id
      courierID
      courier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      userID
      user {
        id
        sub
        firstName
        lastName
        email
        phoneNumber
        profilePic
        address
        exactAddress
        lat
        lng
        isBlocked
        push_token
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      orderID
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      reason
      description
      evidencePhotos
      evidenceVideo
      status
      adminComment
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateCourierReport = /* GraphQL */ `
  subscription OnUpdateCourierReport(
    $filter: ModelSubscriptionCourierReportFilterInput
  ) {
    onUpdateCourierReport(filter: $filter) {
      id
      courierID
      courier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      userID
      user {
        id
        sub
        firstName
        lastName
        email
        phoneNumber
        profilePic
        address
        exactAddress
        lat
        lng
        isBlocked
        push_token
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      orderID
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      reason
      description
      evidencePhotos
      evidenceVideo
      status
      adminComment
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteCourierReport = /* GraphQL */ `
  subscription OnDeleteCourierReport(
    $filter: ModelSubscriptionCourierReportFilterInput
  ) {
    onDeleteCourierReport(filter: $filter) {
      id
      courierID
      courier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      userID
      user {
        id
        sub
        firstName
        lastName
        email
        phoneNumber
        profilePic
        address
        exactAddress
        lat
        lng
        isBlocked
        push_token
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      orderID
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      reason
      description
      evidencePhotos
      evidenceVideo
      status
      adminComment
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreateCourierReview = /* GraphQL */ `
  subscription OnCreateCourierReview(
    $filter: ModelSubscriptionCourierReviewFilterInput
  ) {
    onCreateCourierReview(filter: $filter) {
      id
      courierID
      courier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      userID
      user {
        id
        sub
        firstName
        lastName
        email
        phoneNumber
        profilePic
        address
        exactAddress
        lat
        lng
        isBlocked
        push_token
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      orderID
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      rating
      comment
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateCourierReview = /* GraphQL */ `
  subscription OnUpdateCourierReview(
    $filter: ModelSubscriptionCourierReviewFilterInput
  ) {
    onUpdateCourierReview(filter: $filter) {
      id
      courierID
      courier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      userID
      user {
        id
        sub
        firstName
        lastName
        email
        phoneNumber
        profilePic
        address
        exactAddress
        lat
        lng
        isBlocked
        push_token
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      orderID
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      rating
      comment
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteCourierReview = /* GraphQL */ `
  subscription OnDeleteCourierReview(
    $filter: ModelSubscriptionCourierReviewFilterInput
  ) {
    onDeleteCourierReview(filter: $filter) {
      id
      courierID
      courier {
        id
        sub
        isOnline
        firstName
        lastName
        profilePic
        address
        landMark
        phoneNumber
        email
        courierNIN
        courierNINImage
        bankCode
        bankName
        accountName
        accountNumber
        transportationType
        vehicleClass
        model
        vehicleColour
        plateNumber
        maxiImages
        maxiDescription
        guarantorName
        guarantorLastName
        guarantorProfession
        guarantorNumber
        guarantorRelationship
        guarantorAddress
        guarantorEmail
        guarantorNIN
        guarantorNINImage
        lat
        lng
        heading
        push_token
        isApproved
        approvedById
        currentBatchCount
        currentExpressCount
        currentMaxiCount
        lastBatchAssignedAt
        averageRating
        reviewCount
        totalReports
        statusKey
        walletID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      userID
      user {
        id
        sub
        firstName
        lastName
        email
        phoneNumber
        profilePic
        address
        exactAddress
        lat
        lng
        isBlocked
        push_token
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      orderID
      order {
        id
        recipientName
        recipientNumber
        recipientNumber2
        orderDetails
        originAddress
        originState
        originLat
        originLng
        destinationAddress
        destinationState
        destinationLat
        destinationLng
        tripType
        distance
        transportationType
        vehicleClass
        status
        hasNewOffer
        lastOfferAt
        lastOfferSenderType
        loadCategory
        isInterState
        estimatedMinPrice
        estimatedMaxPrice
        initialOfferPrice
        loadingFee
        unloadingFee
        floorSurcharge
        fragileSurcharge
        extrasTotal
        totalPrice
        operationalFare
        courierEarnings
        commissionAmount
        platformFee
        platformServiceRevenue
        vatAmount
        platformNetRevenue
        deliveryVerificationCode
        declaredWeightBracket
        senderPreTransferPhotos
        senderPreTransferVideo
        senderPreTransferRecordedAt
        senderPreTransferLocalPhotos
        senderPreTransferLocalVideo
        mediaUploadStatus
        courierPreTransferUploadStatus
        courierPostLoadingUploadStatus
        dropoffUploadStatus
        courierPreTransferPhotos
        courierPreTransferVideo
        courierPreTransferRecordedAt
        courierPreTransferLocalPhotos
        courierPreTransferLocalVideo
        courierPostLoadingPhotos
        courierPostLoadingVideo
        courierPostLoadingLocalPhotos
        courierPostLoadingLocalVideo
        dropoffArrivalPhotos
        dropoffArrivalVideo
        dropoffArrivalLocalPhotos
        dropoffArrivalLocalVideo
        postDeliveryPhotos
        postDeliveryVideo
        pickupLoadingResponsibility
        pickupFloorLevel
        pickupFloorLevelPrice
        pickupHasElevator
        dropoffUnloadingResponsibility
        dropoffFloorLevel
        dropoffFloorLevelPrice
        dropoffHasElevator
        acceptedAt
        arrivedPickupAt
        loadingStartedAt
        tripStartedAt
        arrivedDropoffAt
        unloadingCompletedAt
        logisticsCompanyId
        waybillNumber
        waybillPhoto
        logisticsTrackingCode
        logisticsTrackingStatus
        handedOverToLogisticsAt
        logisticsIntakeConfirmedAt
        acceptedOfferID
        paymentStatus
        paymentID
        payoutStatus
        fundsStatus
        assignedCourierId
        assignmentExpiresAt
        assignmentAttempts
        lastAssignedAt
        rejectedCourierIds
        assignmentStatus
        userID
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      rating
      comment
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreateCourier = /* GraphQL */ `
  subscription OnCreateCourier($filter: ModelSubscriptionCourierFilterInput) {
    onCreateCourier(filter: $filter) {
      id
      sub
      isOnline
      firstName
      lastName
      profilePic
      address
      landMark
      phoneNumber
      email
      courierNIN
      courierNINImage
      bankCode
      bankName
      accountName
      accountNumber
      transportationType
      vehicleClass
      model
      vehicleColour
      plateNumber
      maxiImages
      maxiDescription
      guarantorName
      guarantorLastName
      guarantorProfession
      guarantorNumber
      guarantorRelationship
      guarantorAddress
      guarantorEmail
      guarantorNIN
      guarantorNINImage
      lat
      lng
      heading
      push_token
      isApproved
      approvedById
      currentBatchCount
      currentExpressCount
      currentMaxiCount
      lastBatchAssignedAt
      averageRating
      reviewCount
      totalReports
      reviews {
        nextToken
        startedAt
        __typename
      }
      reports {
        nextToken
        startedAt
        __typename
      }
      statusKey
      offers {
        nextToken
        startedAt
        __typename
      }
      orders {
        nextToken
        startedAt
        __typename
      }
      walletID
      wallet {
        id
        ownerID
        ownerType
        balance
        pendingBalance
        totalEarnings
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateCourier = /* GraphQL */ `
  subscription OnUpdateCourier($filter: ModelSubscriptionCourierFilterInput) {
    onUpdateCourier(filter: $filter) {
      id
      sub
      isOnline
      firstName
      lastName
      profilePic
      address
      landMark
      phoneNumber
      email
      courierNIN
      courierNINImage
      bankCode
      bankName
      accountName
      accountNumber
      transportationType
      vehicleClass
      model
      vehicleColour
      plateNumber
      maxiImages
      maxiDescription
      guarantorName
      guarantorLastName
      guarantorProfession
      guarantorNumber
      guarantorRelationship
      guarantorAddress
      guarantorEmail
      guarantorNIN
      guarantorNINImage
      lat
      lng
      heading
      push_token
      isApproved
      approvedById
      currentBatchCount
      currentExpressCount
      currentMaxiCount
      lastBatchAssignedAt
      averageRating
      reviewCount
      totalReports
      reviews {
        nextToken
        startedAt
        __typename
      }
      reports {
        nextToken
        startedAt
        __typename
      }
      statusKey
      offers {
        nextToken
        startedAt
        __typename
      }
      orders {
        nextToken
        startedAt
        __typename
      }
      walletID
      wallet {
        id
        ownerID
        ownerType
        balance
        pendingBalance
        totalEarnings
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteCourier = /* GraphQL */ `
  subscription OnDeleteCourier($filter: ModelSubscriptionCourierFilterInput) {
    onDeleteCourier(filter: $filter) {
      id
      sub
      isOnline
      firstName
      lastName
      profilePic
      address
      landMark
      phoneNumber
      email
      courierNIN
      courierNINImage
      bankCode
      bankName
      accountName
      accountNumber
      transportationType
      vehicleClass
      model
      vehicleColour
      plateNumber
      maxiImages
      maxiDescription
      guarantorName
      guarantorLastName
      guarantorProfession
      guarantorNumber
      guarantorRelationship
      guarantorAddress
      guarantorEmail
      guarantorNIN
      guarantorNINImage
      lat
      lng
      heading
      push_token
      isApproved
      approvedById
      currentBatchCount
      currentExpressCount
      currentMaxiCount
      lastBatchAssignedAt
      averageRating
      reviewCount
      totalReports
      reviews {
        nextToken
        startedAt
        __typename
      }
      reports {
        nextToken
        startedAt
        __typename
      }
      statusKey
      offers {
        nextToken
        startedAt
        __typename
      }
      orders {
        nextToken
        startedAt
        __typename
      }
      walletID
      wallet {
        id
        ownerID
        ownerType
        balance
        pendingBalance
        totalEarnings
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onCreateUser = /* GraphQL */ `
  subscription OnCreateUser($filter: ModelSubscriptionUserFilterInput) {
    onCreateUser(filter: $filter) {
      id
      sub
      firstName
      lastName
      email
      phoneNumber
      profilePic
      address
      exactAddress
      lat
      lng
      isBlocked
      push_token
      courierReviews {
        nextToken
        startedAt
        __typename
      }
      courierReports {
        nextToken
        startedAt
        __typename
      }
      Orders {
        nextToken
        startedAt
        __typename
      }
      payments {
        nextToken
        startedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onUpdateUser = /* GraphQL */ `
  subscription OnUpdateUser($filter: ModelSubscriptionUserFilterInput) {
    onUpdateUser(filter: $filter) {
      id
      sub
      firstName
      lastName
      email
      phoneNumber
      profilePic
      address
      exactAddress
      lat
      lng
      isBlocked
      push_token
      courierReviews {
        nextToken
        startedAt
        __typename
      }
      courierReports {
        nextToken
        startedAt
        __typename
      }
      Orders {
        nextToken
        startedAt
        __typename
      }
      payments {
        nextToken
        startedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
export const onDeleteUser = /* GraphQL */ `
  subscription OnDeleteUser($filter: ModelSubscriptionUserFilterInput) {
    onDeleteUser(filter: $filter) {
      id
      sub
      firstName
      lastName
      email
      phoneNumber
      profilePic
      address
      exactAddress
      lat
      lng
      isBlocked
      push_token
      courierReviews {
        nextToken
        startedAt
        __typename
      }
      courierReports {
        nextToken
        startedAt
        __typename
      }
      Orders {
        nextToken
        startedAt
        __typename
      }
      payments {
        nextToken
        startedAt
        __typename
      }
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
      __typename
    }
  }
`;
